spring.application.name=de3DoAn1Java2
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=document_db;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

upload.dir=D:\\Code\\Java\\eclipse\\eclipseProject\\de3DoAn1Java2\\uploads
server.port=8080

app.server-ip=192.168.1.135

